### ISSUE TITLE
contains mistyped character in master

### ISSUE THREAD

**Issue by Sheile** [opscode-cookbooks/openssl#19]
03e0e9b690fd9db3d81779762c810371f0fe7e1e contains mistyped character in libraries/secure_password.rb.

https://github.com/opscode-cookbooks/openssl/blob/03e0e9b690fd9db3d81779762c810371f0fe7e1e/libraries/secure_password.rb#L1

**Comment by sun16** [comment]
In the meantime, can someone remove or update the problematic 3.0.2 tag that still has the mistyped character?

**Comment by Sheile** [comment]
Removed character at f65e25b082b61bbb3376e486f31202b4cf593119.
I'll close this issue.

Please create new issue if you want discussion about remove problematic tag.
