### ISSUE TITLE
Supermarket and Repository don't match versions

### ISSUE THREAD

**Issue by billmoritz** [opscode-cookbooks/openssl#21]
Seems like there was a release and revert of a 3.0.0 version.  Now there is 3.0.2 on the Supermarket but the Changelog and metadata.rb have 2.0.2.

I'm sure you're just reverting things as fast as possible when there is a breaking release.  I just figured the issue should be raised to put things back in line.

**Comment by charlesjohnson** [comment]
Resolved in #22.
