### ISSUE TITLE
Weirdly-rearranged README

### ISSUE THREAD

**Issue by yozlet** [opscode-cookbooks/openssl#8]
Half of the **Usage** section (about the stats_collector) seems to have fallen to the end of the file.

**Comment by flatrocks** [comment]
Also of related note, usage notes for the secure_password helper method are sort of spread all over since a0b2af5b618547d74e4165870e622ff84c941f12 with the inclusion of the upgrade recipe, and also this:
    ::Chef::Recipe.send(:include, Chef::OpenSSL::Password)
reference should probable be:
    ::Chef::Recipe.send(:include, Opscode::OpenSSL::Password)

**Comment by charlesjohnson** [comment]
Resolved in #26.
